version: '3.8'

services:
    # MySQL Service
    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: todo
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3308:3306"
        networks:
            - app-network

    # PHP with Apache Service
    php-apache:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php-apache
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - "80:80"
        networks:
            - app-network

volumes:
    mysql_data:

networks:
    app-network:
        driver: bridge
